# Generated by Django 3.0.8 on 2020-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_campaign_template_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='political_party',
            field=models.CharField(choices=[('PMDB', 'PMDB - Partido Do Movimento Democrático Brasileiro'), ('PTB', 'PTB - Partido Trabalhista Brasileiro'), ('PDT', 'PDT - Partido Democrático Trabalhista'), ('PT', 'PT - Partido Dos Trabalhadores'), ('DEM', 'DEM - Democratas'), ('PCdoB', 'PCdoB - Partido Comunista Do Brasil'), ('PSB', 'PSB - Partido Socialista Brasileiro'), ('PSDB', 'PSDB - Partido Da Social Democracia Brasileira'), ('PTC', 'PTC - Partido Trabalhista Cristão'), ('PSC', 'PSC - Partido Social Cristão'), ('PMN', 'PMN - Partido Da Mobilização Nacional'), ('PRP', 'PRP - Partido Republicano Progressista'), ('PPS', 'PPS - Partido Popular Socialista'), ('PV', 'PV - Partido Verde'), ('PTdoB', 'PTdoB - Partido Trabalhista Do Brasil'), ('PP', 'PP - Partido Progressista'), ('PSTU', 'PSTU - Partido Socialista Dos Trabalhadores Unificado'), ('PCB', 'PCB - Partido Comunista Brasileiro'), ('PRTB', 'PRTB - Partido Renovador Trabalhista Brasileiro'), ('PHS', 'PHS - Partido Humanista Da Solidariedade'), ('PSDC', 'PSDC - Partido Social Democrata Cristão'), ('PCO', 'PCO - Partido Da Causa Operária'), ('PTN', 'PTN - Partido Trabalhista Nacional'), ('PSL', 'PSL - Partido Social Liberal'), ('PRB', 'PRB - Partido Republicano Brasileiro'), ('PSOL', 'PSOL - Partido Socialismo E Liberdade'), ('PR', 'PR - Partido Da República'), ('PSD', 'PSD - Partido Social Democrático'), ('PPL', 'PPL - Partido Pátria Livre'), ('PEN', 'PEN - Partido Ecológico Nacional'), ('PROS', 'PROS - Partido Republicano Da Ordem Social'), ('SDD\xa0', 'SDD - Solidariedade')], max_length=20, verbose_name='Partido'),
        ),
    ]
